### ISSUE TITLE
The number of examples in file dart-v1.1.1-full-train.json is much smaller than 82,191

### ISSUE THREAD

**Issue by syw1996** [Yale-LILY/dart#4]
The example number of Dart declaimed in Readme file and paper is 82,191, while the actual number of training set in file dart-v1.1.1-full-train.json is 30,526 which is much smaller than 82,191.

**Comment by amritrau** [comment]
Thank you for your message! "Total number of examples" refers to the total number of annotations (not triplesets) across the train, devel, and test sets. Some triplesets may have >1 annotations. There are 30,526 triplesets in DART v1.1.1's train set; there are 82,191 annotations across all parts of DART v1.1.1.
