### ISSUE TITLE
Missing annotations in test set

### ISSUE THREAD

**Issue by montellasebastien** [Yale-LILY/dart#5]
Hi ! :smiley: 

Great data augmentation you've done here!

I have noticed **_missing_** lexicalizations/annotations for some entries in your test set . (For example, eid=Id1392 in your _dart-v1.1.1-full-test.xml_ file).

Do you plan to add those ?

Thanks!

**Comment by linyongnan** [comment]
Thank you for your interest in our dataset! We have updated our repo and there should be no more empty annotations.
